spring:
  application:
    name: elm-backend-food-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?

server:
  port: 10200
  servlet:
    context-path: /api/food
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
logging:
  level:
    org.springframework: debug
    com.neusoft.elmboot.mapper: debug
knife4j:
  enable: true