spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: elm-backend-user-service
          uri: lb://elm-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: elm-backend-food-service
          uri: lb://elm-backend-food-service
          predicates:
            - Path=/api/food/**
        - id: elm-backend-business-service
          uri: lb://elm-backend-business-service
          predicates:
            - Path=/api/business/**
        - id: elm-backend-cart-service
          uri: lb://elm-backend-cart-service
          predicates:
            - Path=/api/cart/**
        - id: elm-backend-deliveryAddress-service
          uri: lb://elm-backend-deliveryAddress-service
          predicates:
            - Path=/api/deliveryAddress/**
        - id: elm-backend-orders-service
          uri: lb://elm-backend-orders-service
          predicates:
            - Path=/api/orders/**
        - id: elm-backend-virtualWallet-service
          uri: lb://elm-backend-virtualWallet-service
          predicates:
            - Path=/api/virtualWallet/**
        - id: elm-backend-point-service
          uri: lb://elm-backend-point-service
          predicates:
            - Path=/api/point/**
  application:
    name: elm-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 14000
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
# 这个是配置不用看token是否合法 直接通过